import type { NextPage } from 'next';
import Head from 'next/head';
import HomeButtons from '../components/home_buttons/home_buttons';
import Profile from '../components/profile/profile';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Wunderbike</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Profile></Profile>
        <HomeButtons></HomeButtons>
      </main>

      <footer className={styles.footer}>
        <a>footer</a>
      </footer>
    </div>
  );
};

export default Home;
