
@host = http://localhost:3001/api
@trick_id = 3c68ef76-c33c-4aee-ab13-871fd6da750b


### public route
GET {{host}}/ping

### authenticated
GET {{host}}/authenticated
Authorization: Bearer {{token}}

### Create a trick
POST {{host}}/tricks
Authorization: Bearer {{token}}
content-type: application/json

{
"title": "Trick number two",
"description": "The second trick ever with a very long description, Lorem ipsum dolor sit amet, consectetur",
"imageUrl": "https://raw.githubusercontent.com/pseudoincorrect/Bariot/main/assets/images/bariot_img.jpg"
} 

### Get a trick
GET {{host}}/tricks/{{trick_id}}
Authorization: Bearer {{token}}

### Get all tricks
GET {{host}}/tricks/all
Authorization: Bearer {{token}}

### Update a trick
PUT {{host}}/tricks/{{trick_id}}
Authorization: Bearer {{token}}
content-type: application/json

{
"title": "Trick One Again",
"description": "The first trick ever updated",
"imageUrl": "https://github.com/pseudoincorrect/Wootch/raw/master/Support/readme_assets/wootch_on.jpg"
} 


### Delete a trick
DELETE {{host}}/tricks/{{trick_id}}
Authorization: Bearer {{token}}