
@host = http://localhost:3000
@userEmail = quidonc@nimportequoi.com
@userPassword = superStrongPassword
@userFullName = Thibaux Toizossi

### Create a user
POST {{host}}/users/register
# Authorization: {{token}}
content-type: application/json

{
"email" : "{{userEmail}}",
"full_name": "{{userFullName}}",
"password" : "{{userPassword}}"
} 
